const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
function validate(info,base){const url=new URL(info.downloadUrl,base);if(info.packageId!=='xyz.ourdays.desktop'||!Number.isSafeInteger(info.versionCode)||info.versionCode<1||!/^\d+\.\d+\.\d+$/.test(info.versionName)||!/^OurDays-[A-Za-z0-9._-]+\.exe$/.test(info.filename)||!/^[a-f0-9]{64}$/.test(info.sha256)||!Number.isSafeInteger(info.size)||info.size<4||info.size>200*1024*1024||url.origin!==new URL(base).origin||url.pathname!=='/api/app/download/'+info.filename||url.search||url.hash||url.username||url.password)throw Error('服务器更新信息无效');return url.href;}
module.exports=function({app,dialog,session,window,serverUrl,build}){let busy=false;return {async check(){if(busy)return;busy=true;try{
 const response=await session.fetch(serverUrl+'api/app/update?platform=windows',{redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('暂时无法读取更新信息');const info=await response.json();if(!info.available){await dialog.showMessageBox(window,{message:'服务器尚未发布 Windows 安装包。'});return;}const url=validate(info,serverUrl);if(info.versionCode<=build){await dialog.showMessageBox(window,{message:'当前已是最新客户端。'});return;}
 const answer=await dialog.showMessageBox(window,{type:'question',title:'版本更新',message:'发现新版本 '+info.versionName+'（构建 '+info.versionCode+'）',detail:String(info.notes||'').slice(0,4000)+'\n下载完成并校验后，可启动安装程序覆盖升级。',buttons:['下载更新','取消'],cancelId:1});if(answer.response!==0)return;
 const directory=path.join(app.getPath('userData'),'updates');fs.mkdirSync(directory,{recursive:true});const file=path.join(directory,info.filename),temp=file+'.'+crypto.randomBytes(8).toString('hex')+'.tmp';
 try{const download=await session.fetch(url,{redirect:'error',signal:AbortSignal.timeout(180000)});if(!download.ok||!download.body)throw Error('安装包下载失败');const hash=crypto.createHash('sha256'),fd=fs.openSync(temp,'wx');let size=0,first=Buffer.alloc(0);try{for await(const chunk of download.body){const bytes=Buffer.from(chunk);size+=bytes.length;if(size>info.size)throw Error('安装包大小不符');if(first.length<2)first=Buffer.concat([first,bytes]).subarray(0,2);hash.update(bytes);fs.writeSync(fd,bytes);}}finally{fs.closeSync(fd);}if(size!==info.size||hash.digest('hex')!==info.sha256||first.toString('ascii')!=='MZ')throw Error('安装包完整性校验失败');if(fs.existsSync(file)){if(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==info.sha256)throw Error('同名安装包内容不同，拒绝覆盖');fs.unlinkSync(temp);}else fs.renameSync(temp,file);
 const install=await dialog.showMessageBox(window,{title:'更新已准备好',message:'安装包已下载并通过校验。安装会关闭朝夕，请先保存正在编辑的内容。',buttons:['安装更新','稍后安装'],cancelId:1});if(install.response===0){const child=spawn(file,[],{detached:true,stdio:'ignore'});child.once('error',()=>dialog.showMessageBox(window,{type:'error',message:'无法启动安装程序，请稍后重试。'}));child.once('spawn',()=>{child.unref();app.quit();});}
 }finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}
 }catch(error){await dialog.showMessageBox(window,{type:'error',title:'检查更新失败',message:error.message});}finally{busy=false;}}};};
module.exports.validate=validate;
